spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1522:xe
    username: C##VISHAL
    password: VISHAL
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
